<?xml version="1.0" encoding="utf-8"?><Database Name="GestionPedidos" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Empresa" Member="Empresas">
    <Type Name="Empresa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Empresa_Empleado" Member="Empleados" ThisKey="Id" OtherKey="empresaId" Type="Empleado" />
    </Type>
  </Table>
  <Table Name="dbo.Empleado" Member="Empleados">
    <Type Name="Empleado">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="empresaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Empleado_CargoEmpleado" Member="CargoEmpleados" ThisKey="Id" OtherKey="empleadoId" Type="CargoEmpleado" />
      <Association Name="Empresa_Empleado" Member="Empresa" ThisKey="empresaId" OtherKey="Id" Type="Empresa" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cargo" Member="Cargos">
    <Type Name="Cargo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreCargo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_CargoEmpleado" Member="CargoEmpleados" ThisKey="Id" OtherKey="cargoId" Type="CargoEmpleado" />
    </Type>
  </Table>
  <Table Name="dbo.CargoEmpleado" Member="CargoEmpleados">
    <Type Name="CargoEmpleado">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="empleadoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cargoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_CargoEmpleado" Member="Cargo" ThisKey="cargoId" OtherKey="Id" Type="Cargo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Empleado_CargoEmpleado" Member="Empleado" ThisKey="empleadoId" OtherKey="Id" Type="Empleado" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>